require("colorbuddy").setup()

local Color = require('colorbuddy').Color

Color.new('white',     '#dae4f0')
Color.new('red',       '#cc6666')
Color.new('pink',      '#fef601')
Color.new('green',     '#71e2ad')
Color.new('yellow',    '#d8c482')
Color.new('blue',      '#6a97d5')
Color.new('aqua',      '#86adcf')
Color.new('cyan',      '#6ab1c5')
Color.new('purple',    '#8e6fbd')
Color.new('violet',    '#ba9ce1')
Color.new('orange',    '#de935f')
Color.new('brown',     '#a3685a')

-- Color.new('white',     '#f2e5bc')
-- Color.new('red',       '#cc6666')
-- Color.new('pink',      '#fef601')
-- Color.new('green',     '#99cc99')
-- Color.new('yellow',    '#f8fe7a')
-- Color.new('blue',      '#81a2be')
-- Color.new('aqua',      '#8ec07c')
-- Color.new('cyan',      '#8abeb7')
-- Color.new('purple',    '#8e6fbd')
-- Color.new('violet',    '#b294bb')
-- Color.new('orange',    '#de935f')
-- Color.new('brown',     '#a3685a')

-- Color.new('seagreen',  '#698b69')
-- Color.new('turquoise', '#698b69')
